apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJiM0JsYm5Ob2FXWjBMWEpsYkdWaGMyVXRaR1YySzI5amJWOWhZMk5sYzNOZlltSTROemt3T1RJeU1qZ3pORGMwTldKaFlXWXpNV1UwTldGa056ZzJaVE02UmpGT1JGTXhOa3hZVWpRMk1sUXdSRXBJVGtVeldrVllXVEJHTmt3d1ZqVTNRazB6VGtkQ1JGaEVXRkpTVWxKSVNqRTVVVTFQTVVNMU9ERkhURE5KUXc9PSIsCiAgICAgICJlbWFpbCI6ICJ0aGFvLnZ1QHN0YWthdGVyLmNvbSIKICAgIH0KICB9Cn0K
kind: Secret
metadata:
  name: multiclusterhub-operator-pull-secret
  namespace: open-cluster-management
type: kubernetes.io/dockerconfigjson

