apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-hub-custom-registry
  labels:
    app: multicluster-hub-custom-registry
spec:
  selector:
    matchLabels:
      app: multicluster-hub-custom-registry
  template:
    metadata:
      labels:
        app: multicluster-hub-custom-registry
    spec:
      containers:
      - name: multicluster-hub-custom-registry
        image: multicluster-hub-custom-registry:1.0.0
        ports:
        - containerPort: 50051
      imagePullSecrets:
      - name: multiclusterhub-operator-pull-secret