kind: Service
apiVersion: v1
metadata:
  name: multicluster-hub-custom-registry
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    app: multicluster-hub-custom-registry