# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: acm-custom-registry
    newName: quay.io/stolostron/acm-custom-registry
    newTag: "2.15.0-SNAPSHOT-2025-07-28-09-24-22"

# list of Resource Config to be Applied
resources:
  - operator-group.yaml
  - subscription.yaml
