apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: <CLUSTER_NAME>
  labels:
    cloud: 'AWS'
    region: '<CLOUD_REGION>'
    environment: 'dev'
    vendor: 'OpenShift'
spec:
  baseDomain: <BASE_DOMAIN>
  clusterName: <CLUSTER_NAME>
  controlPlaneConfig:
    servingCertificates: {}
  installed: false
  platform:
    aws:
      credentialsSecretRef:
        name: <CLUSTER_NAME>-aws-creds
      region: <CLOUD_REGION>
  provisioning:
    installConfigSecretRef:
      name: <CLUSTER_NAME>-install-config
    sshPrivateKeySecretRef:
      name: <CLUSTER_NAME>-ssh-private-key
    imageSetRef:
      name: img4.4.11-x86-64
  pullSecretRef:
    name: <CLUSTER_NAME>-pull-secret