# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true


# list of Resource Config to be Applied
resources:
  - image-content-source-policy.yaml