apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: hive-operator-alpha-community-operators-openshift-marketplace
spec:
  channel: alpha
  config:
    resources: {}
  installPlanApproval: Automatic
  name: hive-operator
  source: community-operators
  sourceNamespace: openshift-marketplace