apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-observability

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: thanos-object-storage
  type: "Opaque"
  files:
    - "thanos.yaml"

resources:
  - pull-secret.yaml
  - example-observability-cr.yaml