---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policies-github-path
  namespace: open-cluster-management
data:
    path: resources/policies
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: demo-policies
  namespace: open-cluster-management
spec:
  channel: open-cluster-management/deploy-demo-policies
  placement:
    local: true
  packageFilter:
    filterRef:
      name: policies-github-path